services:
  llm:
    restart: always
    environment:
      - OLLAMA_MODELS=/mnt/models
      - OLLAMA_MAX_LOADED_MODELS=1 
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_HOST=0.0.0.0:11000
      - OLLAMA_KEEP_ALIVE="10000m"
    volumes:
      - ./ollama_models:/mnt/
    image: ollama/ollama:latest
    ports:
      - 13000:11000
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
